# twbs/Bootstrap repo
# Build using azure pipelines
# For more info on azure pipelines visit: https://azure.microsoft.com/en-in/services/devops/pipelines/

pool:
  vmImage: 'Ubuntu 16.04'

#steps:
#- bash: |
#    which bash
#    echo Hello world
#  displayName: Multiline Bash script
#  env:
#    name: Microsoft  

steps:
- bash: |
    export CHROME_SOURCE_URL=https://dl.google.com/dl/linux/direct/google-chrome-stable_current_amd64.deb
    wget --no-verbose -O /tmp/$(basename $CHROME_SOURCE_URL) $CHROME_SOURCE_URL
  displayName: Install chrome

- checkout: self
  fetchDepth: 3


- bash: |
    export PATH=./node_modules/.bin:$PATH
    echo node version=
    node --version
    echo npm version=
    npm --version
    echo nvm version=
    nvm --version
  displayName: check version