# twbs/Bootstrap repo
# Build using azure pipelines
# For more info on azure pipelines visit: https://azure.microsoft.com/en-in/services/devops/pipelines/
# azure pipelines ruby app: https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/ruby?view=vsts

job: Ubuntu-1604 Job
  pool:
    vmImage: 'Ubuntu 16.04'

  strategy:
    matrix:
      node_6_x:
        node_version: 6.x
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x


  steps:
  - checkout: self
    fetchDepth: 3

  - bash: |
      export CHROME_SOURCE_URL=https://dl.google.com/dl/linux/direct/google-chrome-stable_current_amd64.deb
      wget --no-verbose -O /tmp/$(basename $CHROME_SOURCE_URL) $CHROME_SOURCE_URL
    displayName: Install chrome

  #- bash: |
  #    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  #    source ~/.profile    
  #  displayName: install nvm

  - bash: |
      gem install bundler  
    displayName: install bundler

  - task: NodeTool@0
    displayName: Use Node $(node_version)
    inputs:
      versionSpec: $(node_version)

  - bash: |    
      export PATH=./node_modules/.bin:$PATH
      echo node version=
      node --version
      echo npm version=
      npm --version
      #echo nvm version=
      #nvm --version
    displayName: check version

  - bash: |    
      gem --version
    displayName: test script


  - bash: |
      bundle install --deployment --jobs=3 --retry=3 --clean
    displayName: Bundle Install
