# twbs/Bootstrap repo
# Build using azure pipelines
# For more info on azure pipelines visit: https://azure.microsoft.com/en-in/services/devops/pipelines/
# azure pipelines ruby app: https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/ruby?view=vsts
# how to install: https://github.com/twbs/bootstrap/blob/f83f4ae124fec1012bbecf6d6e748a709031f2fa/site/docs/4.1/getting-started/build-tools.md


# Caching bundle and node modules
# install bundle
# 

pool:
  vmImage: 'Ubuntu 16.04'


steps:

- checkout: self
  fetchDepth: 3

- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.4'
    addToPath: true

- bash: |
    pwd
    ls -ltrh    
    export CHROME_SOURCE_URL=https://dl.google.com/dl/linux/direct/google-chrome-stable_current_amd64.deb
    wget --no-verbose -O /tmp/$(basename $CHROME_SOURCE_URL) $CHROME_SOURCE_URL
  displayName: Install Chrome


- script: |
    gem install bundler  
    bundle install --retry=3 --jobs=4
  displayName: Install Bundler/Dependencies

#- script: |    
#    nvm install 6    
#  displayName: Install NVM
#  failOnStderr: true

- bash: |       
    export PATH=./node_modules/.bin:$PATH
    echo node version=
    node --version
    echo npm version=
    npm --version   
  displayName: Check Node Version

#- bash: |        
#    rm ./package-lock.json
#    npm install jquery@1.9.1 --save
#  displayName: Install Peer dependency
#  failOnStderr: true

- bash: |      
    rm ./package-lock.json  
    npm set audit false
    npm install    
  displayName: Install NPM modules
  failOnStderr: false


- script: |    
    npm test    
    #npm run check-broken-links
  displayName: Run Tests
  failOnStderr: true


  